name: scidvspc
version: "latest-svn"
summary: svidvspc
description: |
  SCID vs. PC is a Chess Toolkit
  Shane's Chess Information Database is a powerful Chess Toolkit, with which one can create huge databases,
  run chess engines, and play casual games against the computer or online with the Free Internet Chess Server. 
  It was originally written by Shane Hudson , and has received strong contribution from Pascal Georges and others.
  Scid vs. PC began with bug-fixes for the computer-versus-player features of Scid (hence the name), but has 
  evolved into a solid alternative with many new features and interfaces. The project is authored by Stevenaaus 
  and numerous contributors
  https://sourceforge.net/p/scidvspc/code/HEAD/tarball
  svn checkout http://svn.code.sf.net/p/scidvspc/code/ scidvspc-code
      TCLTK_BPATH- $SNAP/usr/share/tcltk
      TCL_LIBRARY- $TCLTK_BPATH/tcl8.6:$TCLTK_BPATH/tcl8.6/tcl8:$TCL_LIBRARY
      TK_LIBRARY- $SNAP/usr/share/tcltk/tk8.6:$TK_LIBRARY

grade: devel
confinement: devmode

apps:
  scidvspc:
    command: usr/local/bin/scid
    plugs: [desktop,desktop-legacy,home,x11,unity7]
    environment:
      HKVCTCL_LIBRARY: $SNAP/usr/share/tcltk/tcl8.5:$TCL_LIBRARY
      HKVCTK_LIBRARY: $SNAP/usr/share/tcltk/tk8.5:$TK_LIBRARY
      HKVCTCL_PACKAGE_PATH: "$SNAP/usr/lib/tcltk $SNAP/usr/share/tcltk $SNAP/usr/share/tcltk/tcl8.5 $SNAP/usr/share/tcltk/tcl8.5/tcl8"

parts:
  scidvspc:
    plugin: autotools
    source-type: svn
    source: http://svn.code.sf.net/p/scidvspc/code/
    build-packages:
      - g++
      - make
      - tcl8.5-dev
      - tk8.5-dev
    stage-packages:
      - libtcl8.5
      - libtk8.5
      - tk8.5
      - tcl8.5

  fixit-tcltk:
    plugin: dump
    source: /usr/share/tcltk/
    after: [scidvspc]
    organize: 
      '*': ./usr/lib/

  fixit-tcltk-2:
    plugin: nil
    after: [fixit-tcltk]
    override-prime: |
      sed -i 's/join \//join \/snap\/scidvspc\/current\//' $SNAPCRAFT_PRIME/usr/lib/tcltk/x86_64-linux-gnu/tk8.5/pkgIndex.tcl


