name: scidvspc-hkvc
version: "latest-svn-test-20181112"
version-script: snap/get-version.sh
summary: svidvspc - A Powerfull Chess Tookit
description: |
  SCID vs. PC is a Chess Toolkit
  Shane's Chess Information Database is a powerful Chess Toolkit, with which one can create huge databases,
  run chess engines, and play casual games against the computer or online with the Free Internet Chess Server. 
  It was originally written by Shane Hudson , and has received strong contribution from Pascal Georges and others.
  Scid vs. PC began with bug-fixes for the computer-versus-player features of Scid (hence the name), but has 
  evolved into a solid alternative with many new features and interfaces. The project is authored by Stevenaaus 
  and numerous contributors

  https://sourceforge.net/p/scidvspc/code/HEAD/tarball
  svn checkout http://svn.code.sf.net/p/scidvspc/code/ scidvspc-code

  TCLTK_BPATH- $SNAP/usr/share/tcltk
  TCL_LIBRARY- $TCLTK_BPATH/tcl8.6:$TCL_LIBRARY
  TK_LIBRARY- $TCLTK_BPATH/tk8.6:$TK_LIBRARY

  The <app-$HOME> dir is <user-$HOME>/snap/scidvspc/<version>
  $SNAP_USER_DATA points to this <app's $HOME> dir
  

  NOTE
  This is a experimental snap packaging of scid_vs_pc by HanishKVC

  HISTORY

  1.Q Not able to find init.tcl
  1.1 Set TCL_LIBRARY and TK_LIBRARY wrt $SNAP related tcltk paths,
      solved init.tcl but this popped up msgcat issue, SO
  1.2 Tried copying usr/share/tcltk/* to usr/lib/, 
      but again solved init.tcl but msgcat issue popped up.
  1.3 After finding 2.2 edit tm.tcl soln; 
      Avoid copying usr/share/tcltk/* to usr/lib/, by setting TCL_LIBRARY & TK_LIBRARY
      The more elegant solution.

  2.Q Not able to find msgcat
  2.1 tried updating path in pkgIndex.tcl, didnt help, but as change is logically correct retaining
  2.2 edit tm.tcl to search in $SNAP rooted paths rather than the default / rooted paths fixed the issue 

  TODO
  T01 Have to check if there is a way to persist data across snap remove and snap install. 
      Seems like $SNAP_USER_DATA and $SNAP_USER_COMMON get cleared during snap remove


grade: devel
confinement: strict

apps:
  scidvspc:
    command: usr/local/bin/scid
    plugs: [desktop,desktop-legacy,home,unity7]
    environment:
      TCLTK_BPATH: $SNAP/usr/share/tcltk
      TCL_LIBRARY: $TCLTK_BPATH/tcl8.6:$TCL_LIBRARY
      TK_LIBRARY: $TCLTK_BPATH/tk8.6:$TK_LIBRARY
      HKVCTCL_PACKAGE_PATH: "$SNAP/usr/lib/tcltk $SNAP/usr/share/tcltk $SNAP/usr/share/tcltk/tcl8.6 $SNAP/usr/share/tcltk/tcl8.6/tcl8"

parts:
  scidvspc:
    plugin: autotools
    source-type: svn
    source: http://svn.code.sf.net/p/scidvspc/code/
    build-packages:
      - g++
      - make
      - tcl-dev
      - tk-dev
    stage-packages:
      - stockfish
      - libtcl8.6
      - libtk8.6
      - tk
      - tcl

  fixit-scidvspc:
    plugin: nil
    after: [scidvspc]
    override-prime: |
      sed -i 's/\/usr\//\/snap\/scidvspc-hkvc\/current\/usr\//g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  fruit/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/fruit/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  phalanx/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/phalanx/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  scidlet/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/scidlet/g' $SNAPCRAFT_PRIME/usr/local/bin/scid

  fixit-tcltk:
    plugin: nil
    after: [scidvspc]
    override-prime: |
      sed -i 's/\/usr\//\/snap\/scidvspc-hkvc\/current\/usr\//g' $SNAPCRAFT_PRIME/usr/share/tcltk/tcl8.6/tm.tcl
      sed -i 's/join \//join \/snap\/scidvspc-hkvc\/current\//' $SNAPCRAFT_PRIME/usr/lib/tcltk/x86_64-linux-gnu/tk8.6/pkgIndex.tcl

