name: scidvspc-hkvc
base: core20
version: "latest-svn-test-20201021"
version-script: snap/local/get-version.sh
summary: svidvspc - A Powerfull Chess Tookit
description: |
  SCID vs. PC is a Chess Toolkit
  Shane's Chess Information Database is a powerful Chess Toolkit,
  with which one can create huge databases, run chess engines, and 
  play casual games against the computer or online with the Free 
  Internet Chess Server. It was originally written by Shane Hudson,
  and has received strong contribution from Pascal Georges and 
  others.

  Scid vs. PC began with bug-fixes for the computer-versus-player 
  features of Scid (hence the name), but has evolved into a solid 
  alternative with many new features and interfaces. The project 
  is authored by Stevenaaus and numerous contributors

  ** Source

  https://sourceforge.net/p/scidvspc/code/HEAD/tarball

  svn checkout http://svn.code.sf.net/p/scidvspc/code/ scidvspc-code

  ** Environment

  TCLTK_BPATH= $SNAP/usr/share/tcltk

  TCL_LIBRARY= $TCLTK_BPATH/tcl8.6:$TCL_LIBRARY

  TK_LIBRARY=  $TCLTK_BPATH/tk8.6:$TK_LIBRARY

  TCLLIBPATH=  $SNAP/usr/lib/tcltk $SNAP/usr/lib/tcltk/x86_64-linux-gnu $TCLLIBPATH

  ** Home

  The AppWorkingDir is user's $HOME/snap/scidvspc-hkvc/<revision>

  $SNAP_USER_DATA points to this AppWorkingDir.

  ** ToRun

  type scidvspc-hkvc.scidvspc in a console/terminal

  stockfish available in $SNAP/usr/games/

  ** Sound

  Snap doesnt auto connect the alsa interface to snaps. The user is required
  to explicitly connect the snap's alsa plug to the system's alsa interface.

  For this run the below

  sudo snap connect scidvspc-hkvc:alsa

  NOTE> If there is a issue with sound folders setup, cross verify that the
  sounds folder under options->sounds is set to

  /snap/scidvspc-hkvc/current/usr/local/share/scid/sounds

  ** Source for this snap packaging

  the snap directory used by snapcraft to generate this snap package 
  is in $SNAP/usr/share/doc/scidvspc-hkvc/

  You will also find this among my https://github.com/hanishkvc repositories.

  ** Version

  The snap package version contains the svn revision number of scidvspc
  within it. If manually building the snap, it will try to pick the
  latest revision of the code.
 
  ** NOTE

  This is just a experimental snap packaging of scid_vs_pc by HanishKVC


grade: devel
confinement: strict

apps:
  scidvspc:
    command: usr/local/bin/scid
    plugs: [desktop,desktop-legacy,unity7,home,alsa,audio-playback]
    environment:
      TCLTK_BPATH: $SNAP/usr/share/tcltk
      TCL_LIBRARY: $TCLTK_BPATH/tcl8.6:$TCL_LIBRARY
      TK_LIBRARY: $TCLTK_BPATH/tk8.6:$TK_LIBRARY
      TCLLIBPATH: $SNAP/usr/lib/tcltk $SNAP/usr/lib/tcltk/x86_64-linux-gnu $TCLLIBPATH

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  scidvspc:
    plugin: autotools
    source-type: svn
    source: http://svn.code.sf.net/p/scidvspc/code/
    build-packages:
      - g++
      - make
      - tcl-dev
      - tk-dev
    stage-packages:
      - fontconfig
      - stockfish
      - libtcl8.6
      - libtk8.6
      - tk
      - tcl
      - tcl-snack
      - tdom
    override-pull: |
      snapcraftctl pull
      sed -i 's/install_scid: /install_sound:\n\tinstall -m 755 -d $(SHAREDIR)\/sounds || \/bin\/true\n\tcp -a .\/sounds\/* $(SHAREDIR)\/sounds\/\n\ninstall_scid: install_sound /' $SNAPCRAFT_PART_SRC/Makefile.conf

  fixit-scidvspc:
    plugin: nil
    after: [scidvspc]
    override-prime: |
      sed -i 's/\/usr\//\/snap\/scidvspc-hkvc\/current\/usr\//g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  fruit/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/fruit/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  phalanx/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/phalanx/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/Cmd  scidlet/Cmd  \/snap\/scidvspc-hkvc\/current\/usr\/local\/bin\/scidlet/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      sed -i 's/soundFolder {}/soundFolder "\/snap\/scidvspc-hkvc\/current\/usr\/local\/share\/scid\/sounds"/g' $SNAPCRAFT_PRIME/usr/local/bin/scid
      patch $SNAPCRAFT_PRIME/usr/local/bin/scid ../project/snap/local/patchs/scid.patch
      #rm $SNAPCRAFT_PRIME/usr/local/bin/scid.orig || /bin/true

  fixit-tcltk:
    plugin: nil
    after: [scidvspc]
    override-prime: |
      sed -i 's/\/usr\//\/snap\/scidvspc-hkvc\/current\/usr\//g' $SNAPCRAFT_PRIME/usr/share/tcltk/tcl8.6/tm.tcl
      sed -i 's/join \//join \/snap\/scidvspc-hkvc\/current\//' $SNAPCRAFT_PRIME/usr/lib/tcltk/x86_64-linux-gnu/tk8.6/pkgIndex.tcl

  fixit-src:
    plugin: nil
    after: [scidvspc]
    override-prime: |
      MYDOCPATH=$SNAPCRAFT_PRIME/usr/share/doc/scidvspc-hkvc
      rm -rf $MYDOCPATH || /bin/true
      mkdir $MYDOCPATH
      cp -a ../project/snap $MYDOCPATH/
      rm -rf $MYDOCPATH/snap/.snapcraft
